# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
# 
# Licensed under the GNU Affero General Public License 3.0 (the "License"). 
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any 
# modifications or derivative works of this file must retain this copyright 
# notice, and modified files must contain a notice indicating that they have 
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

name: qa_tutorials

on:
  push:
    branches:
      - qa-pipelines

jobs:
  run_astronomy_tutorial:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest']
        python-version: ['3.8']
    steps:
      - name: Check out head
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install homebrew
        if: matrix.os == 'macos-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install NPM and Yarn on Ubuntu
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          sudo curl -fsSL https://deb.nodesource.com/setup_16.x | sudo /bin/bash -
          sudo apt-get install -y nodejs
          sudo npm install -g yarn
      - name: Build webapp
        run: |
          cd ./covalent_ui/webapp
          yarn install
          yarn build
      - name: Install covalent
        run: |
          pip install -e .
          pip install uvloop
          pip install jupyterlab
      - name: Covalent purge
        run: |
          covalent purge
      - name: Start covalent server
        run: |
          covalent start
      - name: Run stress tests notebook
        run: |
          cd ./tests/stress_tests
          jupyter-nbconvert --to notebook --execute stress.ipynb
      - name: Stop covalent
        run: |
          covalent stop